### PR TITLE
Regenerated models after updating ORCID http to https

### PR DESCRIPTION
**Pull request by dustine32**
Using same upstream JSON file as in the last PR #4 but with code updated to use "https" instead of "http" for ORCIDs.

### CODE REVIEW

**Comment by ukemi** [comment]
@dustine32 , for the ones that would become duplicates, were the duplicates removed? When I looked at the file that was used for the original import, it looked like there was both the http and the https versions for most if not all of them. It was duplicated for the ones I looked at for MGI.

**Comment by dustine32** [comment]
@ukemi Oh yeah, this PR is just for the SynGO models.

But for the dupes in MGI, it seems that minerva will sort these dupes out. I test loaded one of these into a Noctua instance and then checked the exported OWL. In the fixed imported TTL files now having two "https" entries for the same ORCID after the `sed` update, the exported OWL only shows a single "https" entry. I'm guessing the minerva/blazegraph load operation might be "unique-ifying" duplicate triples like `gomodel:MGI_MGI_101884  contributor  https://orcid.org/0000-0002-1558-1958`, which is the behavior we want for this.

**Comment by ukemi** [comment]
Sounds perfect @dustine32. Just wanted to be sure we were covering all the bases. I opened a ticket in the MGI tracker, but then noticed that I had opened one a while ago to convert all the http OrcIDs for our curation staff to https. The ticket was closed, so I assume it was done and won't be a problem on our side. Thanks!

**Comment by kltm** [comment]
Tying back to https://github.com/geneontology/go-site/issues/1907

**Pull request merged**
